In [1]:
import pandas as pd

# NWHL_all_games

In [2]:
NWHL_all = pd.read_csv('../Data/nwhl_games_all.csv')

In [3]:
NWHL_all.columns

Index(['Season', 'Player', 'Team', 'position', 'game_id', 'game_date',
       'home_team', 'away_team', 'G', 'A1', 'A2', 'PTS', 'PrPTS', 'GS', 'SOG',
       'eGF', 'eGA', 'GF.', 'PPG', 'PPA1', 'PPA2', 'SHG', 'SHA1', 'SHA2',
       'FOW', 'FOL', 'PIM', 'Blk', 'TO', 'SV', 'GA'],
      dtype='object')

In [4]:
NWHL_all.shape

(3862, 31)

In [5]:
NWHL_all[NWHL_all['Player'] == 'Hilary Knight']

,Season,Player,Team,position,game_id,game_date,home_team,away_team,G,A1,...,SHG,SHA1,SHA2,FOW,FOL,PIM,Blk,TO,SV,GA
25,2015,Hilary Knight,BOS,F,14668259,2016-08-19,BUF,BOS,2,0,...,0,0,0,0,0,0,0,0,0,0
59,2015,Hilary Knight,BOS,F,14690190,2016-08-22,MET,BOS,0,1,...,0,0,0,0,0,2,0,0,0,0
79,2015,Hilary Knight,BOS,F,14690359,2016-08-22,BUF,BOS,0,0,...,0,0,1,0,0,0,0,0,0,0
136,2015,Hilary Knight,BOS,F,14694328,2016-08-23,MET,BOS,1,1,...,1,1,0,0,0,0,0,0,0,0
155,2015,Hilary Knight,BOS,F,14694401,2016-08-23,BOS,MET,1,1,...,0,0,0,0,0,0,0,0,0,0
237,2015,Hilary Knight,BOS,F,14752032,2016-08-30,BOS,BUF,1,2,...,0,0,0,0,0,2,0,0,0,0
255,2015,Hilary Knight,BOS,F,14752514,2016-09-02,BOS,MET,2,0,...,0,0,0,0,0,2,0,0,0,0
302,2015,Hilary Knight,BOS,F,14800529,2016-09-02,BOS,BUF,1,0,...,0,0,0,0,0,0,0,0,0,0
347,2015,Hilary Knight,BOS,F,14800650,2016-09-02,BOS,BUF,1,1,...,0,1,0,0,0,0,0,0,0,0
408,2015,Hilary Knight,BOS,F,14801353,2016-09-02,BOS,MET,1,2,...,0,0,0,0,0,0,0,0,0,0
445,2015,Hilary Knight,BOS,F,14814740,2016-09-02,BOS,CTW,1,1,...,0,0,0,0,0,0,0,0,0,0
508,2015,Hilary Knight,BOS,F,14814946,2016-09-02,CTW,BOS,2,1,...,0,1,0,0,0,0,0,0,0,0
532,2015,Hilary Knight,BOS,F,14817367,2016-09-03,MET,BOS,1,0,...,0,0,0,0,0,0,0,0,0,0
585,2015,Hilary Knight,BOS,F,14820870,2016-09-03,BOS,CTW,0,1,...,0,0,0,0,0,0,0,0,0,0
598,2015,Hilary Knight,BOS,F,14821029,2016-09-03,CTW,BOS,1,2,...,0,1,0,0,0,2,0,0,0,0
635,2015,Hilary Knight,BOS,F,14822377,2016-09-03,BUF,BOS,0,1,...,0,0,0,0,0,0,0,0,0,0
1036,2016,Hilary Knight,BOS,F,14689501,2016-11-12,BOS,CTW,1,0,...,0,0,0,0,0,0,2,0,0,0
1057,2016,Hilary Knight,BOS,F,14689501,2016-11-12,BOS,CTW,0,0,...,0,0,0,0,0,0,0,0,0,0
1612,2016,Hilary Knight,BOS,F,14689561,2017-01-21,MET,BOS,1,0,...,0,0,0,0,0,0,0,0,0,0
1661,2016,Hilary Knight,BOS,F,14689574,2017-01-15,CTW,BOS,1,0,...,0,0,0,0,1,0,2,0,0,0
1709,2016,Hilary Knight,BOS,F,14689578,2017-01-27,CTW,BOS,0,0,...,0,0,0,0,1,0,0,0,0,0
1739,2016,Hilary Knight,BOS,F,14689578,2017-01-27,CTW,BOS,0,0,...,0,0,0,0,0,0,0,0,0,0
1936,2016,Hilary Knight,BOS,F,14689601,2017-02-04,BOS,CTW,0,0,...,0,0,0,1,0,2,0,0,0,0
1991,2016,Hilary Knight,BOS,F,14689606,2017-02-18,BOS,BUF,1,1,...,0,0,0,0,0,2,1,0,0,0
2011,2016,Hilary Knight,BOS,F,14689606,2017-02-18,BOS,BUF,0,0,...,0,0,0,0,0,0,0,0,0,0
2090,2016,Hilary Knight,BOS,F,14689618,2017-02-24,CTW,BOS,1,1,...,1,0,1,2,0,0,0,0,0,0
2175,2016,Hilary Knight,BOS,F,14689624,2017-03-04,BOS,MET,2,0,...,0,0,0,0,0,0,2,0,0,0
2200,2016,Hilary Knight,BOS,F,14689624,2017-03-04,BOS,MET,0,0,...,0,0,0,0,0,0,0,0,0,0
2222,2016,Hilary Knight,BOS,F,14689629,2017-03-05,BOS,BUF,1,0,...,0,0,0,0,0,0,1,0,0,0
2246,2016,Hilary Knight,BOS,F,14689629,2017-03-05,BOS,BUF,0,0,...,0,0,0,0,0,0,0,0,0,0
2270,2016,Hilary Knight,BOS,F,14689652,2017-03-12,MET,BOS,0,1,...,0,0,0,0,0,0,4,0,0,0

In [6]:
NWHL_all.rename(columns={'position': 'Pos', 'A1': 'A', 'A2':'A1', 'PTS':'P', 'PrPTS':'P1', 'PPA1':'PPA', 
                         'PPA2':'PPA1', 'SHA1': 'SHA', 'SHA2':'SHA1'}, inplace=True)

In [7]:
NWHL_all.columns

Index(['Season', 'Player', 'Team', 'Pos', 'game_id', 'game_date', 'home_team',
       'away_team', 'G', 'A', 'A1', 'P', 'P1', 'GS', 'SOG', 'eGF', 'eGA',
       'GF.', 'PPG', 'PPA', 'PPA1', 'SHG', 'SHA', 'SHA1', 'FOW', 'FOL', 'PIM',
       'Blk', 'TO', 'SV', 'GA'],
      dtype='object')

In [8]:
NWHL_all_format = NWHL_all[['Season', 'Player', 'Team', 'Pos', 'G', 'A', 'A1', 'P', 'P1', 'PPG', 'PPA', 'PPA1', 'SHG',
                           'SHA', 'SHA1', 'Blk']]

In [9]:
NWHL_all_format.head()

,Season,Player,Team,Pos,G,A,A1,P,P1,PPG,PPA,PPA1,SHG,SHA,SHA1,Blk
0,2015,Anya Battaglino,CTW,F|D,0,0,0,0,0,0,0,0,0,0,0,0
1,2015,Ashley Johnston,MET,D,0,0,0,0,0,0,0,0,0,0,0,0
2,2015,Brooke Ammerman,MET,F,1,0,0,1,1,0,0,0,0,0,0,0
3,2015,Danielle Ward,CTW,F,0,0,0,0,0,0,0,0,0,0,0,0
4,2015,Elena Orlando,MET,D,0,0,0,0,0,0,0,0,0,0,0,0

In [10]:
Knight = NWHL_all_format[NWHL_all_format['Player'] == 'Hilary Knight']
Knight

,Season,Player,Team,Pos,G,A,A1,P,P1,PPG,PPA,PPA1,SHG,SHA,SHA1,Blk
25,2015,Hilary Knight,BOS,F,2,0,0,2,2,0,0,0,0,0,0,0
59,2015,Hilary Knight,BOS,F,0,1,1,2,1,0,0,0,0,0,0,0
79,2015,Hilary Knight,BOS,F,0,0,1,1,0,0,0,0,0,0,1,0
136,2015,Hilary Knight,BOS,F,1,1,0,2,2,1,0,0,1,1,0,0
155,2015,Hilary Knight,BOS,F,1,1,0,2,2,1,1,0,0,0,0,0
237,2015,Hilary Knight,BOS,F,1,2,0,3,3,0,0,0,0,0,0,0
255,2015,Hilary Knight,BOS,F,2,0,0,2,2,0,0,0,0,0,0,0
302,2015,Hilary Knight,BOS,F,1,0,0,1,1,0,0,0,0,0,0,0
347,2015,Hilary Knight,BOS,F,1,1,0,2,2,0,0,0,0,1,0,0
408,2015,Hilary Knight,BOS,F,1,2,0,3,3,0,1,0,0,0,0,0
445,2015,Hilary Knight,BOS,F,1,1,1,3,2,0,0,0,0,0,0,0
508,2015,Hilary Knight,BOS,F,2,1,0,3,3,0,0,0,0,1,0,0
532,2015,Hilary Knight,BOS,F,1,0,0,1,1,0,0,0,0,0,0,0
585,2015,Hilary Knight,BOS,F,0,1,1,2,1,0,0,0,0,0,0,0
598,2015,Hilary Knight,BOS,F,1,2,0,3,3,0,0,0,0,1,0,0
635,2015,Hilary Knight,BOS,F,0,1,0,1,1,0,0,0,0,0,0,0
1036,2016,Hilary Knight,BOS,F,1,0,0,1,1,0,0,0,0,0,0,2
1057,2016,Hilary Knight,BOS,F,0,0,0,0,0,0,0,0,0,0,0,0
1612,2016,Hilary Knight,BOS,F,1,0,0,1,1,0,0,0,0,0,0,0
1661,2016,Hilary Knight,BOS,F,1,0,0,1,1,1,0,0,0,0,0,2
1709,2016,Hilary Knight,BOS,F,0,0,1,1,0,0,0,0,0,0,0,0
1739,2016,Hilary Knight,BOS,F,0,0,0,0,0,0,0,0,0,0,0,0
1936,2016,Hilary Knight,BOS,F,0,0,0,0,0,0,0,0,0,0,0,0
1991,2016,Hilary Knight,BOS,F,1,1,0,2,2,0,0,0,0,0,0,1
2011,2016,Hilary Knight,BOS,F,0,0,0,0,0,0,0,0,0,0,0,0
2090,2016,Hilary Knight,BOS,F,1,1,1,3,2,1,0,0,1,0,1,0
2175,2016,Hilary Knight,BOS,F,2,0,0,2,2,0,0,0,0,0,0,2
2200,2016,Hilary Knight,BOS,F,0,0,0,0,0,0,0,0,0,0,0,0
2222,2016,Hilary Knight,BOS,F,1,0,2,3,1,0,0,0,0,0,0,1
2246,2016,Hilary Knight,BOS,F,0,0,0,0,0,0,0,0,0,0,0,0
2270,2016,Hilary Knight,BOS,F,0,1,0,1,1,0,1,0,0,0,0,4

In [11]:
Knight_2015 = Knight[Knight['Season'] == 2015]
Knight_2015['G'].sum()

15

In [12]:
Knight_2015.shape

(16, 16)

In [13]:
Knight_2015['A'].sum()

14

In [14]:
NWHL_all_format_2015 = NWHL_all_format[NWHL_all_format['Season'] == 2015]
NWHL_all_format_2015.shape

(664, 16)

In [15]:
player_name = NWHL_all_format_2015['Player'].unique()

In [16]:
player_name.tolist()

['Anya Battaglino',
 'Ashley Johnston',
 'Brooke Ammerman',
 'Danielle Ward',
 'Elena Orlando',
 'Jaimie Leonoff',
 'Jessica Koizumi',
 'Jordan Brickner',
 'Kaleigh Fratkin',
 'Kelli Stack',
 'Kelly Babstock',
 'Kiira Dosdall',
 'Ludmila Belyakova',
 'Madison Packer',
 'Micaela Long',
 'Molly Engstrom',
 'Nana Fujimoto',
 'Shiann Darkangelo',
 'Alyssa Gagliardi',
 'Amanda Pelkey',
 'Brianna Decker',
 'Brianne Mclaughlin',
 'Brittany Ott',
 'Emily Field',
 'Emily Pfalzer',
 'Hilary Knight',
 'Jillian Dempsey',
 'Jordan Smelker',
 'Kacey Bellamy',
 'Kelley Steadman',
 'Marissa Gedman',
 'Meghan Duggan',
 'Zoe Hickel',
 'Alyssa Wohlfeiler',
 'Annmarie Cellino',
 'Chelsea Laden',
 'Hailey Browne',
 'Kate Buesser',
 'Lindsay Berman',
 'Maggie Giamo',
 'Sam Faber',
 'Tatiana Rafter',
 'Amber Moore',
 'Blake Bolden',
 'Corinne Buie',
 'Gabie Figueroa',
 'Lauren Slebodnick',
 'Moran Fritz-Ward',
 'Shenae Lundberg',
 'Gigi Marvin',
 'Hayley Williams',
 'Kourtney Kunichika',
 'Megan Bozek',
 'Rachel Llanes',
 'Shelby Bram',
 'Brittany Dougherty',
 'Janine Weber',
 'Meghan Fardelmann',
 'Nicole Stock',
 'Devon Skeats',
 'Jessica Fickel',
 'Kimberly Sass',
 'Paige Harrington',
 'Shannon Doyle',
 'Tara Tomimoto',
 'Beth Hanrahan',
 'Bray Ketchum',
 'Casey Pickett',
 'Celeste Brown',
 'Sydney Kidd',
 'Taylor Holze',
 'Amanda Makel',
 'Kelly McDonald',
 'Yekaterina Smolentseva',
 'Hannah McGowan',
 'Jenny Scrivens',
 'Kelly Cooke',
 'Erin Zach',
 'Meagan Mangene',
 'Kelsie Fralick',
 'Lindsay Grigg']

In [17]:
len(player_name)

81

In [18]:
NWHL_all_format_2015.columns

Index(['Season', 'Player', 'Team', 'Pos', 'G', 'A', 'A1', 'P', 'P1', 'PPG',
       'PPA', 'PPA1', 'SHG', 'SHA', 'SHA1', 'Blk'],
      dtype='object')

In [19]:
NWHL_all_format_2015.insert(1, 'League', ['NWHL']*len(NWHL_all_format_2015))
NWHL_all_format_2015.insert(5, 'GP', [None]*len(NWHL_all_format_2015))

In [20]:
NWHL_all_format_2015.columns

Index(['Season', 'League', 'Player', 'Team', 'Pos', 'GP', 'G', 'A', 'A1', 'P',
       'P1', 'PPG', 'PPA', 'PPA1', 'SHG', 'SHA', 'SHA1', 'Blk'],
      dtype='object')

In [21]:
one_name = ['Hilary Knight', 'Madison Packer']

In [22]:
Season_2015_agg = pd.DataFrame([], columns = [NWHL_all_format_2015.columns])
Season_2015_agg

Empty DataFrame
Columns: [(Season,), (League,), (Player,), (Team,), (Pos,), (GP,), (G,), (A,), (A1,), (P,), (P1,), (PPG,), (PPA,), (PPA1,), (SHG,), (SHA,), (SHA1,), (Blk,)]
Index: []

In [23]:
columns = NWHL_all_format_2015.columns.tolist()
column_slice = columns[6:]
column_slice

['G', 'A', 'A1', 'P', 'P1', 'PPG', 'PPA', 'PPA1', 'SHG', 'SHA', 'SHA1', 'Blk']

In [24]:
for name in one_name:
    df = NWHL_all_format_2015[NWHL_all_format_2015['Player'] == name]
    player_stat_fin = [2015, 'NWHL']
    player_stat_col = NWHL_all_format_2015.columns[:6]
    player_stat = df.iloc[0][2:5]
    player_stat2 = player_stat.tolist()
    player_stat2.insert(0, 2015)
    player_stat2.insert(1, 'NWHL')
    player_stat2.append(df.shape[0])
    #Season_2015_agg.loc[0] = player_stat2
    for col in column_slice:
        val = df[col].sum()
        player_stat2.append(val)
    player_stat3 = pd.Series(player_stat2, index=columns)
    NWHL_all_format_2015 = NWHL_all_format_2015.append(player_stat3, ignore_index=True)
#Season_2015_agg.append(player_stat2, ignore_index=True)
#player_stat2
NWHL_all_format_2015.shape

(666, 18)

In [25]:
Knight2 = NWHL_all_format_2015[(NWHL_all_format_2015['Player'] == 'Hilary Knight')|(NWHL_all_format_2015['Player'] == 'Madison Packer') ]
Knight2.shape

(30, 18)

In [26]:
Knight2

,Season,League,Player,Team,Pos,GP,G,A,A1,P,P1,PPG,PPA,PPA1,SHG,SHA,SHA1,Blk
13,2015,NWHL,Madison Packer,MET,F,None,0,0,0,0,0,0,0,0,0,0,0,0
25,2015,NWHL,Hilary Knight,BOS,F,None,2,0,0,2,2,0,0,0,0,0,0,0
59,2015,NWHL,Hilary Knight,BOS,F,None,0,1,1,2,1,0,0,0,0,0,0,0
64,2015,NWHL,Madison Packer,MET,F,None,0,0,0,0,0,0,0,0,0,0,0,0
79,2015,NWHL,Hilary Knight,BOS,F,None,0,0,1,1,0,0,0,0,0,0,1,0
136,2015,NWHL,Hilary Knight,BOS,F,None,1,1,0,2,2,1,0,0,1,1,0,0
140,2015,NWHL,Madison Packer,MET,F,None,1,0,0,1,1,0,0,0,0,0,0,0
155,2015,NWHL,Hilary Knight,BOS,F,None,1,1,0,2,2,1,1,0,0,0,0,0
160,2015,NWHL,Madison Packer,MET,F,None,1,0,0,1,1,0,0,0,0,0,0,0
221,2015,NWHL,Madison Packer,MET,F,None,1,0,0,1,1,0,0,0,0,0,0,0
237,2015,NWHL,Hilary Knight,BOS,F,None,1,2,0,3,3,0,0,0,0,0,0,0
255,2015,NWHL,Hilary Knight,BOS,F,None,2,0,0,2,2,0,0,0,0,0,0,0
292,2015,NWHL,Madison Packer,MET,F,None,0,0,0,0,0,0,0,0,0,0,0,0
302,2015,NWHL,Hilary Knight,BOS,F,None,1,0,0,1,1,0,0,0,0,0,0,0
321,2015,NWHL,Madison Packer,MET,F,None,0,0,1,1,0,0,0,0,0,0,0,0
347,2015,NWHL,Hilary Knight,BOS,F,None,1,1,0,2,2,0,0,0,0,1,0,0
371,2015,NWHL,Madison Packer,MET,F,None,0,0,0,0,0,0,0,0,0,0,0,0
408,2015,NWHL,Hilary Knight,BOS,F,None,1,2,0,3,3,0,1,0,0,0,0,0
445,2015,NWHL,Hilary Knight,BOS,F,None,1,1,1,3,2,0,0,0,0,0,0,0
476,2015,NWHL,Madison Packer,MET,F,None,0,1,0,1,1,0,1,0,0,0,0,0
496,2015,NWHL,Madison Packer,MET,F,None,0,0,1,1,0,0,0,0,0,0,0,0
508,2015,NWHL,Hilary Knight,BOS,F,None,2,1,0,3,3,0,0,0,0,1,0,0
532,2015,NWHL,Hilary Knight,BOS,F,None,1,0,0,1,1,0,0,0,0,0,0,0
574,2015,NWHL,Madison Packer,MET,F,None,0,0,0,0,0,0,0,0,0,0,0,0
585,2015,NWHL,Hilary Knight,BOS,F,None,0,1,1,2,1,0,0,0,0,0,0,0
598,2015,NWHL,Hilary Knight,BOS,F,None,1,2,0,3,3,0,0,0,0,1,0,0
635,2015,NWHL,Hilary Knight,BOS,F,None,0,1,0,1,1,0,0,0,0,0,0,0
658,2015,NWHL,Madison Packer,MET,F,None,0,0,1,1,0,0,0,1,0,0,0,0
664,2015,NWHL,Hilary Knight,BOS,F,16,15,14,4,33,29,2,2,0,1,4,1,0
665,2015,NWHL,Madison Packer,MET,F,12,3,1,3,7,4,0,1,1,0,0,0,0

In [27]:
Knight3 = Knight2[Knight2['GP'].notnull()]

In [28]:
Knight3

,Season,League,Player,Team,Pos,GP,G,A,A1,P,P1,PPG,PPA,PPA1,SHG,SHA,SHA1,Blk
664,2015,NWHL,Hilary Knight,BOS,F,16,15,14,4,33,29,2,2,0,1,4,1,0
665,2015,NWHL,Madison Packer,MET,F,12,3,1,3,7,4,0,1,1,0,0,0,0